version: "3" # composeファイルのバーション指定

services:
  app: # service名
    build: ./docker/app # ビルドに使用するDockerfileがあるディレクトリ指定
    container_name: go-service
    ports:
      - "8090"
    depends_on:
      - mysql
    tty: true # コンテナの起動永続化
    volumes:
      - ./:/go/src/gotrading # マウントディレクトリ指定
    environment:
      TZ: Asia/Tokyo
  nginx:
    build: ./docker/nginx
    container_name: nginx-service
    ports:
      - "8080:8080"
    depends_on:
      - "app"
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: trading
    ports:
      - "3306:3306"
