version: "3" # composeファイルのバーション指定

services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    ports:
      - "8090"
    depends_on:
      - mysql
    tty: true # コンテナの起動永続化
    volumes:
      - ./:/go/src/gotrading # マウントディレクトリ指定
    # command: |
    #   "./gotrading"
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - "app"
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: trading
    ports:
      - "3306:3306"
