version: "3" # composeファイルのバーション指定
services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kenji
      MYSQL_PASSWORD: tama0413
      MYSQL_DATABASE: trading
    ports:
      - "3306:3306"
