version: "3" # composeファイルのバーション指定

services:
  app: # service名
    build: ./docker/app # ビルドに使用するDockerfileがあるディレクトリ指定
    container_name: go-service
    ports:
      - "8090"
    depends_on:
      - mysql
    tty: true # コンテナの起動永続化
    volumes:
      - ./:/go/src/gotrading # マウントディレクトリ指定
    environment:
      TZ: Asia/Tokyo
      API_KEY:
      API_SECRET:
      LOG_FILE: gotrading.log
      PRODUCT_CODE: BTC_JPY
      TRADE_DURATION: 1m
      BACK_TEST: "true"
      USE_PERCENT: 0.9
      DATA_LIMIT: 365
      STOP_LIMIT_PERCENT: 0.8
      NUM_RANKING: 2
      DEADLINE: 3600
      DB_NAME: trading
      DB_USER_NAME:
      DB_PASSWORD:
      SQL_DRIVER: mysql
      PORT: 8090
  nginx:
    build: ./docker/nginx
    container_name: nginx-service
    ports:
      - "8080:8080"
    depends_on:
      - "app"
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
