version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
  slack: circleci/slack@3.4.2
workflows:
  app-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_DOMAIN
          dockerfile: ./docker/app/Dockerfile
          repo: "${AWS_RESOURCE_NAME_PREFIX}-image"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: "go-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-ecs-cluster"
          container-image-name-updates: "container=trading-go,tag=${CIRCLE_SHA1}"
          container-env-var-updates: "container=trading-go,name=API_KEY,value=${API_KEY}"
  nginx-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_DOMAIN
          dockerfile: ./docker/nginx/Dockerfile
          repo: nginx-image
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: "go-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-ecs-cluster"
          container-image-name-updates: "container=trading-nginx,tag=${CIRCLE_SHA1}"
